//Values

let js = "Amazing";
//The numbers in the parantez below are some values actually
console.log(40 + 8 + 23 - 10);

//even the name "jonas" below is a value

// a value is the smallest form of information that we have in JS */

console.log('Joans');
console.log(23);

let firstname = "Matilda";
// we declared a variable called 'first name' and gave a value of 'Jonas'  to it.
console.log(firstname);
console.log(firstname);
console.log(firstname);
// 2
let jonas_matilda = "JM";
let $function = 27;
let person = 'Jonas';
//3
let PI = 3.1415;
//5
let myfirstjob = 'programmer';
let mycurrentjob = 'teacher';
// rules to naming variables 

/*
1- watch out not to write a number in the beginning of a variables name. 

2- variables can only contain $ , underline , score and words. 

3- do not start a varaiable name with an UPPERCASE letter 

4- variables with upper case are reserved for constants. 
5 -  make sure that the variable is namable 
*/
